In [1]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [5]:
import numpy as np

In [9]:
arr = np.array(my_list)

In [11]:
arr

array([1, 2, 3])

In [13]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [35]:
#first arg is rows, then 2nd is columns
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
#number of brackets denotes number of dimensions
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [227]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [49]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [53]:
np.random.rand(2)

array([0.59127924, 0.18889405])

In [55]:
np.random.rand(5,5)

array([[0.09364203, 0.38600159, 0.74750787, 0.60976981, 0.18289701],
       [0.41336491, 0.39754166, 0.98764057, 0.39443171, 0.83825707],
       [0.91079503, 0.25608793, 0.62414139, 0.85440294, 0.12723177],
       [0.19691704, 0.44006119, 0.04492035, 0.33186271, 0.26360658],
       [0.77810604, 0.28576744, 0.87672635, 0.48343344, 0.19262976]])

In [57]:
## does a bell curve of random
np.random.randn(2)

array([0.94552011, 0.36660709])

In [59]:
np.random.randn(4,4)

array([[-1.4111464 , -1.89257485,  1.40453846,  1.3338457 ],
       [ 0.55829481, -0.93996739, -1.22086033, -0.38352714],
       [ 0.50014405,  1.14558323, -0.88321082, -0.69554511],
       [ 0.73275097,  0.36996053, -0.90432529, -0.35320324]])

In [63]:
# low is inclusive high is exclusive, is range and then how many random numbers you want
np.random.randint(1,100,10)

array([44, 52, 16, 10, 94, 48, 83, 22, 42, 22])

In [65]:
arr = np.arange(25)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
ranarr = np.random.randint(0,50,10)

In [85]:
ranarr

array([35, 36,  2, 45, 29, 17, 14, 29, 49,  5])

In [77]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
ranarr.max()

49

In [87]:
ranarr.min()

2

In [89]:
#returns index location of max value in array
ranarr.argmax()

8

In [91]:
ranarr.argmin()

2

In [93]:
arr.shape

(25,)

In [95]:
ranarr.shape

(10,)

In [97]:
arr = arr.reshape(5,5)

In [99]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [101]:
arr.shape

(5, 5)

In [105]:
arr.dtype

dtype('int32')

In [109]:
from numpy.random import randint

In [111]:
randint(2,10)

4

Lesson 2

In [114]:
arr = np.arange(0,11)

In [116]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
arr[8]

8

In [120]:
arr[1:5]

array([1, 2, 3, 4])

In [122]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [124]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
arr[0:5] = 100

In [128]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [130]:
arr = np.arange(0,11)

In [132]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
slice_of_arr = arr[0:6]

In [136]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [140]:
slice_of_arr[:] = 99

In [142]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [144]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [146]:
arr_copy = arr.copy()

In [148]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [158]:
arr_copy[:] = 100

In [160]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [164]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [166]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [176]:
arr_2d[0][0]


5

In [180]:
arr_2d[1][1]

25

In [182]:
arr_2d[2][1]

40

In [184]:
#use comma syntax
arr_2d[2,1]

40

In [186]:
arr_2d[1,2]

30

In [188]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [190]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [192]:
arr = np.arange(1,11)

In [194]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [198]:
bool_arr = arr > 5

In [200]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [202]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [204]:
print(arr[bool_arr])

[ 6  7  8  9 10]


In [206]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [208]:
arr[arr<3]

array([1, 2])

In [212]:
arr_2d = np.arange(50).reshape(5,10)

arr_2d

In [215]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [219]:
arr_2d[1:4,3:7]

array([[13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])